/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ricksy.business;

import org.junit.Test;
import static org.junit.Assert.*;


public class CreditCardTest {

    @Test
    public void getNumberTest() {
        CreditCard creditcard = new CreditCard("Antonio", "56789654321");
        assertEquals("56789654321", creditcard.number());
    }

    @Test
    public void getCreditTest() {
        CreditCard creditcard = new CreditCard("Abradolph Lincler", "4916119711304546");
        assertEquals(3000, creditcard.credit(), 0);
    }

    @Test
    public void paySiHayDineroTest() {
        CreditCard creditcard = new CreditCard("Devil Morty", "7534123415");
        creditcard.pay(200);
        assertTrue(true);
    }

    @Test public void payNoHayDineroTest() {
        CreditCard creditcard = new CreditCard("Devil Morty", "7534123415");
        creditcard.pay(3000);
        assertTrue(false);
    }
}
